# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-16 13:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('folio', '0005_auto_20200216_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='users',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
