# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-16 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0007_auto_20200216_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='kent.jpg', upload_to='pictures/'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_pic',
            field=models.ImageField(default='kent.jpg', upload_to='pictures/'),
        ),
    ]
