# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-19 08:12
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0009_auto_20200216_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
