# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-19 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0012_auto_20200219_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_pic',
            field=models.ImageField(default='one.jpg', upload_to='pictures/'),
        ),
    ]
